// console.log(5+ +1)
// console.log("A"+ +"B")
// console.log(5+ +"A")
// console.log(5+ -1)
// console.log(0.1 + 0.2)

console.log("A" + 1 + "B")
console.log("A" - 1 + "B")
console.log("A" - "C" + "B")
console.log("A" - 5 + "-1")